require(foreign)
require(stringi)
require(stringr)

#Datos DENUE estatal

denue21 <- read.dbf("C:\\Users\\Ruben\\Documents\\Datos\\denue_21_shp\\conjunto_de_datos\\denue_inegi_21.dbf")

corta.dat <- subset(denue21, select = c("id", "codigo_act", "per_ocu",  
                                        "cod_postal", "cve_ent","cve_mun", "cve_loc","ageb", 
                                        "manzana", "latitud", "longitud", "fecha_alta"))


corta.nom <- subset(denue21, select = c("id", "nom_estab", "raz_social", 
                                        "nombre_act", "entidad", "municipio",
                                        "localidad"))

corta.nom$nom_estab <- tolower(corta.nom$nom_estab)
corta.nom$raz_social <- tolower(corta.nom$raz_social)

corta.nom$nom_estab <- as.character(corta.nom$nom_estab)
corta.nom$entidad <- as.character(corta.nom$entidad)
corta.nom$raz_social <- as.character(corta.nom$raz_social)
corta.nom$nombre_act <- as.character(corta.nom$nombre_act)
corta.nom$localidad <- as.character(corta.nom$localidad)
corta.nom$municipio <- as.character(corta.nom$municipio)

Encoding(corta.nom$nom_estab) <- "latin1"
Encoding(corta.nom$raz_social) <- "latin1"
Encoding(corta.nom$localidad) <- "latin1"
Encoding(corta.nom$entidad) <- "latin1"
Encoding(corta.nom$municipio) <- "latin1"
Encoding(corta.nom$nombre_act) <- "latin1"

corta.nom$nom_estab <- stri_trans_general(corta.nom$nom_estab, "latin-ascii")
corta.nom$raz_social <- stri_trans_general(corta.nom$raz_social, "latin-ascii")
corta.nom$localidad <-stri_trans_general(corta.nom$localidad, "latin-ASCII")
corta.nom$entidad <-stri_trans_general(corta.nom$entidad, "latin-ASCII")
corta.nom$municipio <-stri_trans_general(corta.nom$municipio, "latin-ASCII")
corta.nom$nombre_act <-stri_trans_general(corta.nom$nombre_act, "latin-ASCII")

uni2latex <- function(x){
  x <- gsub(' +',' ', x, fixed = TRUE)
  x <- gsub("^\\s+|\\s+$", "", x, fixed = TRUE)
  x <- gsub("^\\s +|\\s +$", "", x, fixed = TRUE)
  x <- gsub("(.*?)($|'|[[:punct:]]+?)(.*?)", "\\1", x, fixed = TRUE)
  x <- gsub("a\u0083a\u0080\u009c", "o", x, fixed = TRUE)
  x <- gsub("\u0083\u0080", "e", x, fixed = TRUE)
  x <- gsub("a\u0083i¿ 1/2", "i", x, fixed = TRUE)
  x <- gsub("a\u0083a\u0080°", "e", x, fixed = TRUE)
  x <- gsub("a\u0083a¡", "u", x, fixed = TRUE)
  x <- gsub("a\u0083a\u0080\u0098", "n", x, fixed = TRUE)
  x <- gsub("A\u0083A³", "o", x, fixed = TRUE)
  x <- gsub("A\u0083A-", "i", x, fixed = TRUE)
  x <- gsub("\u0083A±", "n", x, fixed = TRUE)
  x <- gsub("A\u0083A¡", "a", x, fixed = TRUE)
  x <- gsub("A\u0083A(C)", "e", x, fixed = TRUE)
  x <- gsub("A\u0083Aº", "u", x, fixed = TRUE)
  x <- gsub("A\u0083a\u0080\u009c", "O", x, fixed = TRUE)
  x <- gsub("a\u0083a\u0080\u0099", "o", x, fixed = TRUE)
  x <- gsub("a\u0083a\u0093", "u", x, fixed = TRUE)
  x <- gsub("a\u0082a°", "°", x, fixed = TRUE)
  x <- gsub("a\u0082a´", "\'", x, fixed = TRUE)
  x <- gsub("a\u0082a¨", "\"", x, fixed = TRUE)
  x <- gsub("a\u0082a¿", "¿", x, fixed = TRUE)
  x <- gsub("a\u0083a-", "i", x, fixed = TRUE)
  x <- gsub("a\u0083a\u0080¹", "e", x, fixed = TRUE)
  x <- gsub("a\u0083a³", "o", x, fixed = TRUE)
  x <- gsub("a\u0083a\u0084¢", "c", x, fixed = TRUE)
  x <- gsub("tortilll?","tortill", x, fixed = TRUE)
  x <- gsub("elaboracioon","elaboracion", x, fixed = TRUE)
  x <- gsub("elaboracon","elaboracion", x, fixed = TRUE)
  x <- gsub("elabortacon","elaboracion", x, fixed = TRUE)
  x <- gsub("de chaquira","", x, fixed = TRUE)
  x <- gsub("de chaquira,","", x, fixed = TRUE)
  x <- gsub("para dama","", x, fixed = TRUE)
  x <- gsub("para caballero","", x, fixed = TRUE)
  x <- gsub("para bebe","", x, fixed = TRUE)
  x <- gsub("para toda la familia","", x, fixed = TRUE)
  x <- gsub("fernindez", "fernandez", x, fixed = TRUE)
  x <- gsub("hernindez", "hernandez", x, fixed = TRUE)
  x <- gsub("gonzilez", "gonzalez", x, fixed = TRUE)
  x <- gsub("gonziles", "gonzales", x, fixed = TRUE)
  x <- gsub("crusticeos", "crustaceos", x, fixed = TRUE)
  x <- gsub("hidriulico", "hidraulico", x, fixed = TRUE)
  x <- gsub("automitico", "automatico", x, fixed = TRUE)
  x <- gsub("automitica", "automatica", x, fixed = TRUE)
  x <- gsub("miscelinea", "miscelanea", x, fixed = TRUE)
  x <- gsub("^abarrotes?", "miscelanea", x, fixed = TRUE)
  x <- gsub("^abarrotes[:space:]", "miscelanea", x, fixed = TRUE)
  x <- gsub("mecinico", "mecanico", x, fixed = TRUE)
  x <- gsub("sinchez", "sanchez", x, fixed = TRUE)
  x <- gsub("mirquez", "marquez", x, fixed = TRUE)
  x <- gsub("farmacias", "farmacia", x, fixed = TRUE)
  x <- gsub("farmicia", "farmacia", x, fixed = TRUE)
  x <- gsub("farmicias", "farmacia", x, fixed = TRUE)
  x <- gsub("pediitra", "pediatria", x, fixed = TRUE)
  x <- gsub("pediatra", "pediatria", x, fixed = TRUE)
  x <- gsub("pediitrico", "pediatria", x, fixed = TRUE)
  x <- gsub("pediatrico", "pediatria", x, fixed = TRUE)
  x <- gsub("pediatrica", "pediatria", x, fixed = TRUE)
  x <- gsub("ingel", "angel", x, fixed = TRUE)
  x <- gsub("miscelania","miscelanea", x, fixed = TRUE)
  x <- gsub("miselania","miscelanea", x, fixed = TRUE)
  x <- gsub("misceleanea","miscelanea", x, fixed = TRUE)
  x <- gsub("miscelaneo","miscelanea", x, fixed = TRUE)
  x <- gsub("miscelineo","miscelanea", x, fixed = TRUE)
  x <- gsub("miscelinez","miscelanea", x, fixed = TRUE)
  x <- gsub("miselanea","miscelanea", x, fixed = TRUE)
  x <- gsub("miscelinia","miscelanea", x, fixed = TRUE)
  x <- gsub("mscelinia","miscelanea", x, fixed = TRUE)
  x <- gsub("tendajon", "miscelanea", x, fixed = TRUE)
  x <- gsub("tendejon", "miscelanea", x, fixed = TRUE)
  x <- gsub("tendenjon", "miscelanea", x, fixed = TRUE)
  x <- gsub("mscelanea","miscelanea", x, fixed = TRUE)
  x <- gsub("micelanea","miscelanea", x, fixed = TRUE)
  x <- gsub("cooperativa escolar","tienda escolar", x, fixed = TRUE)
  x <- gsub("tiendita","tienda", x, fixed = TRUE)
  x <- gsub("miscelanea de abarrotes","miscelanea", x, fixed = TRUE)
  x <- gsub("comercio al por menor en tiendas de abarrotes, ultramarinos y miscelaneas","miscelanea", x, fixed = TRUE)
  x <- gsub("tienda de abarrotes","miscelanea", x, fixed = TRUE)
  x <- gsub("tiendita de abarrotes","miscelanea", x, fixed = TRUE)
  x <- gsub("tendajon de abarrotes","miscelanea", x, fixed = TRUE)
  x <- gsub("tendejon de abarrotes","miscelanea", x, fixed = TRUE)
  x <- gsub("venta de abarrotes","miscelanea", x, fixed = TRUE)
  x <- gsub("miscelanea, ultramarinos y miscelaneas","miscelanea", x, fixed = TRUE)
  x <- gsub("abogada?","abogado", x, fixed = TRUE)
  x <- gsub("abogada[:space:]","abogado", x, fixed = TRUE)
  x <- gsub("abogados","abogado", x, fixed = TRUE)
  x <- gsub("bufetes juridicos","abogado", x, fixed = TRUE)
  x <- gsub("bufete juridico","abogado", x, fixed = TRUE)
  x <- gsub("despacho juridico","abogado", x, fixed = TRUE)
  x <- gsub("despacho de abogado","abogado", x, fixed = TRUE)
  x <- gsub("administrcion","administracion", x, fixed = TRUE)
  x <- gsub("alfarero","alfareria", x, fixed = TRUE)
  x <- gsub("administrcion","administracion", x, fixed = TRUE)
  x <- gsub("artesanias","artesania", x, fixed = TRUE)
  x <- gsub("aretesania","artesania", x, fixed = TRUE)
  x <- gsub("artesanas","artesania", x, fixed = TRUE)
  x <- gsub("artesana?","artesania", x, fixed = TRUE)
  x <- gsub("artesanis","artesania", x, fixed = TRUE)
  x <- gsub("artesano?","artesania", x, fixed = TRUE)
  x <- gsub("elaboracion de artesania","artesania", x, fixed = TRUE)
  x <- gsub("tienda de artesania","artesania", x, fixed = TRUE)
  x <- gsub("elaboracion de artesania","artesania", x, fixed = TRUE)
  x <- gsub("taller de artesania","artesania", x, fixed = TRUE)
  x <- gsub("auto lavado","autolavado", x, fixed = TRUE)
  x <- gsub("auto-lavado","autolavado", x, fixed = TRUE)
  x <- gsub("lavado de autos","autolavado", x, fixed = TRUE)
  x <- gsub("restaurantes con servicio de preparacion de antojitos","antojitos", x, fixed = TRUE)
  x <- gsub("preparacion de antojitos","antojitos", x, fixed = TRUE)
  x <- gsub("antojitos mexicanos","antojitos", x, fixed = TRUE)
  x <- gsub("venta de antojitos","antojitos", x, fixed = TRUE)
  x <- gsub("venta de abarrotes, ultramarinos y miscelaneas","miscelanea", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilleria de maiz y molienda de nixtamal","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilleria de mano","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilleria de maiz","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion y tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria manual","tortilleria", x, fixed = TRUE)
  x <- gsub("venta de tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("venta de tortilleria hechas a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("taller de hojalateria y pintura","hojalateria", x, fixed = TRUE)
  x <- gsub("hojalateria y pintura","hojalateria", x, fixed = TRUE)
  x <- gsub("hojalateria y pintura automotriz","hojalateria", x, fixed = TRUE)
  x <- gsub("hojalateria y pintura en general","hojalateria", x, fixed = TRUE)
  x <- gsub("servicio de hojalateria y pintura","hojalateria", x, fixed = TRUE)
  x <- gsub("taller hojalateria","hojalateria", x, fixed = TRUE)
  x <- gsub("hojalateria y pintura de automoviles","hojalateria", x, fixed = TRUE)
  x <- gsub("hojalateria y pintura de automoviles y camiones","hojalateria", x, fixed = TRUE)
  x <- gsub("renovadora de calzado","reparacion de calzado", x, fixed = TRUE)
  x <- gsub("reparadora de calzado","reparacion de calzado", x, fixed = TRUE)
  x <- gsub("taller de hojalateria y pintura automotriz","hojalateria", x, fixed = TRUE)
  x <- gsub("para hombre","", x, fixed = TRUE)
  x <- gsub("para mujer","", x, fixed = TRUE)
  x <- gsub("taller hojalateria","hojalateria", x, fixed = TRUE)
  x <- gsub("venta de dulces","dulceria", x, fixed = TRUE)
  x <- gsub("tienda de dulceria","dulceria", x, fixed = TRUE)
  x <- gsub("dulceria tipicos","dulceria", x, fixed = TRUE)
  x <- gsub("distribuidor autorizado telcel","telcel", x, fixed = TRUE)
  x <- gsub("distribuidor de telcel","telcel", x, fixed = TRUE)
  x <- gsub("distribuidora telcel","telcel", x, fixed = TRUE)
  x <- gsub("tienda telcel","telcel", x, fixed = TRUE)
  x <- gsub("venta de celulares telcel","telcel", x, fixed = TRUE)
  x <- gsub("venta de telefonos celulares telcel","telcel", x, fixed = TRUE)
  x <- gsub("venta de telefonos telcel","telcel", x, fixed = TRUE)
  x <- gsub("tienda de telcel","telcel", x, fixed = TRUE)
  x <- gsub("recargas de telcel","telcel", x, fixed = TRUE)
  x <- gsub("modulo de telcel","telcel", x, fixed = TRUE)
  x <- gsub("telcel distribuidor","telcel", x, fixed = TRUE)
  x <- gsub("celulares telcel","telcel", x, fixed = TRUE)
  x <- gsub("subdistribuidor telcel","telcel", x, fixed = TRUE)
  x <- gsub("tienda de telefonos telcel","telcel", x, fixed = TRUE)
  x <- gsub("venta de fichas telcel","telcel", x, fixed = TRUE)
  x <- gsub("tienda de telefonos y tiempo aire telcel","telcel", x, fixed = TRUE)
  x <- gsub("punto de venta telcel","telcel", x, fixed = TRUE)
  x <- gsub("recargas telcel","telcel", x, fixed = TRUE)
  x <- gsub("telcel distribuidor autorizado","telcel", x, fixed = TRUE)
  x <- gsub("centro de atencion telcel","telcel", x, fixed = TRUE)
  x <- gsub("tienda distribuidor telcel","telcel", x, fixed = TRUE)
  x <- gsub("telcel","distribuidor telcel", x, fixed = TRUE)
  x <- gsub("expendio de pan","panaderia", x, fixed = TRUE)
  x <- gsub("venta de pan","panaderia", x, fixed = TRUE)
  x <- gsub("panaleria","panaderia", x, fixed = TRUE)
  x <- gsub("^pan?","panaderia", x, fixed = TRUE)
  x <- gsub("horno de pan","panaderia", x, fixed = TRUE)
  x <- gsub("hornito de pan","panaderia", x, fixed = TRUE)
  x <- gsub("elaboracion de pan","panaderia", x, fixed = TRUE)
  # x <- gsub("automecanica","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("automecanico","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("automecinica","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("taller mecanico","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("servicio mecanico","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("mecinica?","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("mecanica?","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("meanico","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("mecanico","taller mecanico automotriz", x, fixed = TRUE)
  # x <- gsub("mecanicos","taller mecanico automotriz", x, fixed = TRUE)
  x <- gsub("blockera","bloquera", x, fixed = TRUE)
  x <- gsub("blokera","bloquera", x, fixed = TRUE)
  x <- gsub("bodega-almacen","bodega", x, fixed = TRUE)
  x <- gsub("almacen?","bodega", x, fixed = TRUE)
  x <- gsub("almacen[:space:]","bodega", x, fixed = TRUE)
  x <- gsub("boleria","bolero", x, fixed = TRUE)
  x <- gsub("bolereo","bolero", x, fixed = TRUE)
  x <- gsub("bonetera","boneteria", x, fixed = TRUE)
  x <- gsub("bulcanizadora","vulcanizadora", x, fixed = TRUE)
  x <- gsub("^internet[:space:]","cafe internet", x, fixed = TRUE)
  x <- gsub("^internet?","cafe internet", x, fixed = TRUE)
  x <- gsub("^internek?","cafe internet", x, fixed = TRUE)
  x <- gsub("^inernet?","cafe internet", x, fixed = TRUE)
  x <- gsub("cafeinternet","cafe internet", x, fixed = TRUE)
  x <- gsub("^ciber?","cafe internet", x, fixed = TRUE)
  x <- gsub("ciber cafe","cafe internet", x, fixed = TRUE)
  x <- gsub("^cyber?","cafe internet", x, fixed = TRUE)
  x <- gsub("cyber cafe","cafe internet", x, fixed = TRUE)
  x <- gsub("cybercafe","cafe internet", x, fixed = TRUE)
  x <- gsub("cibercafe","cafe internet", x, fixed = TRUE)
  x <- gsub("^cafe?","cafeteria", x, fixed = TRUE)
  x <- gsub("^cyber?","cafe internet", x, fixed = TRUE)
  x <- gsub("carneceria","carniceria", x, fixed = TRUE)
  x <- gsub("carnes","carniceria", x, fixed = TRUE)
  x <- gsub("carnecerias","carniceria", x, fixed = TRUE)
  x <- gsub("carpintera","carpinteria", x, fixed = TRUE)
  x <- gsub("carpintero","carpinteria", x, fixed = TRUE)
  x <- gsub("carpitenria","carpinteria", x, fixed = TRUE)
  x <- gsub("carpiteria","carpinteria", x, fixed = TRUE)
  x <- gsub("taller de carpinteria","carpinteria", x, fixed = TRUE)
  x <- gsub("venta de tacos","taqueria", x, fixed = TRUE)
  x <- gsub("cerimica","ceramica", x, fixed = TRUE)
  x <- gsub("cerrajerias","cerrajeria", x, fixed = TRUE)
  x <- gsub("chicharines","botana", x, fixed = TRUE)
  x <- gsub("chicharrines","botana", x, fixed = TRUE)
  x <- gsub("chicharrones","botana", x, fixed = TRUE)
  x <- gsub("chicharroneria","botana", x, fixed = TRUE)
  x <- gsub("botanas","botana", x, fixed = TRUE)
  x <- gsub("venta de botana","botana", x, fixed = TRUE)
  x <- gsub("papas fritas","botana", x, fixed = TRUE)
  x <- gsub("venta de chicharron","botana", x, fixed = TRUE)
  x <- gsub("jehovi","jehova", x, fixed = TRUE)
  x <- gsub("fritura","botana", x, fixed = TRUE)
  x <- gsub("frituras","botana", x, fixed = TRUE)
  x <- gsub("venta de papas","botana", x, fixed = TRUE)
  x <- gsub("consultorios","consultorio", x, fixed = TRUE)
  x <- gsub("contador","contabilidad", x, fixed = TRUE)
  x <- gsub("contable","contabilidad", x, fixed = TRUE)
  x <- gsub("contadora","contabilidad", x, fixed = TRUE)
  x <- gsub("servicios de contabilidad y auditoria","contabilidad", x, fixed = TRUE)
  x <- gsub("despacho contabilidad","contabilidad", x, fixed = TRUE)
  x <- gsub("copiadora","copias", x, fixed = TRUE)
  x <- gsub("copiadoras","copias", x, fixed = TRUE)
  x <- gsub("taller de costura","costura", x, fixed = TRUE)
  x <- gsub("composturas de ropa","costura", x, fixed = TRUE)
  x <- gsub("compostura de ropa","costura", x, fixed = TRUE)
  x <- gsub("servicio de costura","costura", x, fixed = TRUE)
  x <- gsub("reparacion de ropa","costura", x, fixed = TRUE)
  x <- gsub("reparacion de bicicletas","taller de bicicletas", x, fixed = TRUE)
  x <- gsub("costurera","costura", x, fixed = TRUE)
  x <- gsub("costurero","costura", x, fixed = TRUE)
  x <- gsub("costureras","costura", x, fixed = TRUE)
  x <- gsub("^costuras?","costura", x, fixed = TRUE)
  x <- gsub("costureros","costura", x, fixed = TRUE)
  x <- gsub("modista","costura", x, fixed = TRUE)
  x <- gsub("modisto","costura", x, fixed = TRUE)
  x <- gsub("sastre?","costura", x, fixed = TRUE)
  x <- gsub("sastreria","costura", x, fixed = TRUE)
  x <- gsub("dentistas","dentista", x, fixed = TRUE)
  x <- gsub("dentistaes","dentista", x, fixed = TRUE)
  x <- gsub("consultorios dentales del sector privado","dentista", x, fixed = TRUE)
  x <- gsub("consultorio dentista del sector privado","dentista", x, fixed = TRUE)
  x <- gsub("consultorio dentista","dentista", x, fixed = TRUE)
  x <- gsub("clinica dentista","dentista", x, fixed = TRUE)
  x <- gsub("estomatologia","dentista", x, fixed = TRUE)
  x <- gsub("dental","dentista", x, fixed = TRUE)
  x <- gsub("estomatologo","dentista", x, fixed = TRUE)
  x <- gsub("desayunos","desayunador", x, fixed = TRUE)
  x <- gsub("desayundor","desayunador", x, fixed = TRUE)
  x <- gsub("dulces","dulceria", x, fixed = TRUE)
  x <- gsub("elaborcion","elaboracion", x, fixed = TRUE)
  x <- gsub("electronicas","electronico", x, fixed = TRUE)
  x <- gsub("electronica?","electronico", x, fixed = TRUE)
  x <- gsub("electronicos","electronico", x, fixed = TRUE)
  x <- gsub("esteticas","estetica", x, fixed = TRUE)
  x <- gsub("peluqueria","estetica", x, fixed = TRUE)
  x <- gsub("estetica unisex","estetica", x, fixed = TRUE)
  x <- gsub("estetita","estetica", x, fixed = TRUE)
  x <- gsub("salones y clinicas de belleza y estetica","estetica", x, fixed = TRUE)
  x <- gsub("estropajos","estropajo", x, fixed = TRUE)
  x <- gsub("fantasias","fantasia", x, fixed = TRUE)
  x <- gsub("farma-ahorro","farmahorro", x, fixed = TRUE)
  x <- gsub("farma ahorro","farmahorro", x, fixed = TRUE)
  x <- gsub("floristeria","floreria", x, fixed = TRUE)
  x <- gsub("^flores?","floreria", x, fixed = TRUE)
  x <- gsub("floteria","floreria", x, fixed = TRUE)
  x <- gsub("fondita","cocina economica", x, fixed = TRUE)
  x <- gsub("fonda","cocina economica", x, fixed = TRUE)
  x <- gsub("fotocopiado","copias", x, fixed = TRUE)
  x <- gsub("gasolineria","gasolinera", x, fixed = TRUE)
  x <- gsub("generico","genericos", x, fixed = TRUE)
  x <- gsub("gineco-obstetra","ginecologia", x, fixed = TRUE)
  x <- gsub("ginecobstetra","ginecologia", x, fixed = TRUE)
  x <- gsub("ginecoobstetra","ginecologia", x, fixed = TRUE)
  x <- gsub("ginecobstetricia","ginecologia", x, fixed = TRUE)
  x <- gsub("ginecologo","ginecologia", x, fixed = TRUE)
  x <- gsub("ginecologa","ginecologia", x, fixed = TRUE)
  x <- gsub("hamburguesa?","hamburguesas", x, fixed = TRUE)
  x <- gsub("hamburgueza?","hamburguesas", x, fixed = TRUE)
  x <- gsub("herbalift","herbalife", x, fixed = TRUE)
  x <- gsub("herbalefe","herbalife", x, fixed = TRUE)
  x <- gsub("herbalafife","herbalife", x, fixed = TRUE)
  x <- gsub("herblife","herbalife", x, fixed = TRUE)
  x <- gsub("herblife","herbalife", x, fixed = TRUE)
  x <- gsub("desayunos herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("productos herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("venta de productos herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("club herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("club de nutricion herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("club nutricional herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("nutricion herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("venta de herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("desayunador herbalife","herbalife", x, fixed = TRUE)
  x <- gsub("homeopatico","homeopata", x, fixed = TRUE)
  x <- gsub("homeopatia","homeopata", x, fixed = TRUE)
  x <- gsub("huesera","quiropractico", x, fixed = TRUE)
  x <- gsub("huesero","quiropractico", x, fixed = TRUE)
  x <- gsub("se curan huesos","quiropractico", x, fixed = TRUE)
  x <- gsub("osteopata","quiropractico", x, fixed = TRUE)
  x <- gsub("quiropractica","quiropractico", x, fixed = TRUE)
  x <- gsub("grifico","grafico", x, fixed = TRUE)
  x <- gsub("grifica","grafico", x, fixed = TRUE)
  x <- gsub("fotografica","fotos", x, fixed = TRUE)
  x <- gsub("fotografico","fotos", x, fixed = TRUE)
  x <- gsub("fotografo","fotos", x, fixed = TRUE)
  x <- gsub("fotografa","fotos", x, fixed = TRUE)
  x <- gsub("fotografia","fotos", x, fixed = TRUE)
  x <- gsub("grifico","grafico", x, fixed = TRUE)
  x <- gsub("herreia","herreria", x, fixed = TRUE)
  x <- gsub("herrero","herreria", x, fixed = TRUE)
  x <- gsub("herrreria","herreria", x, fixed = TRUE)
  x <- gsub("taller de herreria","herreria", x, fixed = TRUE)
  x <- gsub("hojalteria","hojalateria", x, fixed = TRUE)
  x <- gsub("hojalatero","hojalateria", x, fixed = TRUE)
  x <- gsub("imss-oportunidades","imss", x, fixed = TRUE)
  x <- gsub("isste","issste", x, fixed = TRUE)
  x <- gsub("ivin","ivan", x, fixed = TRUE)
  x <- gsub("jarceria","jarcieria", x, fixed = TRUE)
  x <- gsub("jarsieria","jarcieria", x, fixed = TRUE)
  x <- gsub("jugos","jugueria", x, fixed = TRUE)
  x <- gsub("jugeria","jugueria", x, fixed = TRUE)
  x <- gsub("venta de jugueria","jugueria", x, fixed = TRUE)
  x <- gsub("jugueria y licuados","jugueria", x, fixed = TRUE)
  x <- gsub("juegueria","jugueria", x, fixed = TRUE)
  x <- gsub("juguetes","jugueteria", x, fixed = TRUE)
  x <- gsub("ladrillo crudo","ladrillera", x, fixed = TRUE)
  x <- gsub("ladrillos","ladrillera", x, fixed = TRUE)
  x <- gsub("ladrillo","ladrillera", x, fixed = TRUE)
  x <- gsub("ladrillra","ladrillera", x, fixed = TRUE)
  x <- gsub("horno de ladrillera","ladrillera", x, fixed = TRUE)
  x <- gsub("horno de tabique","ladrillera", x, fixed = TRUE)
  x <- gsub("elaboracion de ladrillera","ladrillera", x, fixed = TRUE)
  x <- gsub(", excepto de bebe y lenceria","", x, fixed = TRUE)
  x <- gsub("maderia","madederia", x, fixed = TRUE)
  x <- gsub("maiceria","maiz", x, fixed = TRUE)
  x <- gsub("mais","maiz", x, fixed = TRUE)
  x <- gsub("mirmol","marmol", x, fixed = TRUE)
  x <- gsub("maquila?","maquiladora", x, fixed = TRUE)
  x <- gsub("maquilera","maquiladora", x, fixed = TRUE)
  x <- gsub("maquilero","maquiladora", x, fixed = TRUE)
  x <- gsub("taller de maquiladora","maquiladora", x, fixed = TRUE)
  x <- gsub("maquiladora de ropa","maquiladora", x, fixed = TRUE)
  x <- gsub("maquiniria","maquinaria", x, fixed = TRUE)
  x <- gsub("medicos","medico", x, fixed = TRUE)
  x <- gsub("medicas","medico", x, fixed = TRUE)
  x <- gsub("medica","medico", x, fixed = TRUE)
  x <- gsub("medica","medico", x, fixed = TRUE)
  x <- gsub("consultorio de medicina general del sector privado","medico general", x, fixed = TRUE)
  x <- gsub("medicina general","medico general", x, fixed = TRUE)
  x <- gsub("consultorio medicina general","medico general", x, fixed = TRUE)
  x <- gsub("consultorio de medicina general","medico general", x, fixed = TRUE)
  x <- gsub("consultorio de medicina general privado","medico general", x, fixed = TRUE)
  x <- gsub("consultorio medico general","medico general", x, fixed = TRUE)
  x <- gsub("consultorio de medicina especializada del sector privado","medico especialista", x, fixed = TRUE)
  x <- gsub("huesos","quiropractico", x, fixed = TRUE)
  x <- gsub("maquinas","maquinaria", x, fixed = TRUE)
  x <- gsub("miquina","maquinaria", x, fixed = TRUE)
  x <- gsub("miquinas","maquinaria", x, fixed = TRUE)
  x <- gsub("maquina","maquinaria", x, fixed = TRUE)
  x <- gsub("metalica","metalico", x, fixed = TRUE)
  x <- gsub("metalicas","metalico", x, fixed = TRUE)
  x <- gsub("metalicos","metalico", x, fixed = TRUE)
  x <- gsub("metilica","metalico", x, fixed = TRUE)
  x <- gsub("metilicas","metalico", x, fixed = TRUE)
  x <- gsub("metilicos","metalico", x, fixed = TRUE)
  x <- gsub("metilico","metalico", x, fixed = TRUE)
  x <- gsub("minisuper","tienda de conveniencia", x, fixed = TRUE)
  x <- gsub("mini super","tienda de conveniencia", x, fixed = TRUE)
  x <- gsub("supercito","tienda de conveniencia", x, fixed = TRUE)
  # x <- gsub("mecanico?","taller mecanico automotriz", x, fixed = TRUE)
  x <- gsub("molinos","molino", x, fixed = TRUE)
  x <- gsub("notriologo","nutriologia", x, fixed = TRUE)
  x <- gsub("notriologos","nutriologia", x, fixed = TRUE)
  x <- gsub("notriologa","nutriologia", x, fixed = TRUE)
  x <- gsub("notriologas","nutriologia", x, fixed = TRUE)
  x <- gsub("oftalmico","oftalmologia", x, fixed = TRUE)
  x <- gsub("oftalmica","oftalmologia", x, fixed = TRUE)
  x <- gsub("oftalmicas","oftalmologia", x, fixed = TRUE)
  x <- gsub("oftalmicos","oftalmologia", x, fixed = TRUE)
  x <- gsub("oftalmologo","oftalmologia", x, fixed = TRUE)
  x <- gsub("oftalmologa","oftalmologia", x, fixed = TRUE)
  x <- gsub("oftalmologos","oftalmologia", x, fixed = TRUE)
  x <- gsub("oftalmologas","oftalmologia", x, fixed = TRUE)
  x <- gsub("ortodoncistas","ortodoncia", x, fixed = TRUE)
  x <- gsub("ortodoncista","ortodoncia", x, fixed = TRUE)
  x <- gsub("ortodontica","ortodoncia", x, fixed = TRUE)
  x <- gsub("papelerias","papeleria", x, fixed = TRUE)
  x <- gsub("papelria","papeleria", x, fixed = TRUE)
  x <- gsub("pelucqueria","estetica", x, fixed = TRUE)
  x <- gsub("peluqeria?","estetica", x, fixed = TRUE)
  x <- gsub("periodicos","periodico", x, fixed = TRUE)
  x <- gsub("^periodicos?","periodico", x, fixed = TRUE)
  x <- gsub("^periodico?"," puesto de periodico", x, fixed = TRUE)
  x <- gsub("planchaduria","planchado", x, fixed = TRUE)
  x <- gsub("playera?","playeras", x, fixed = TRUE)
  x <- gsub("plistico?","plastico", x, fixed = TRUE)
  x <- gsub("plisticos","plastico", x, fixed = TRUE)
  x <- gsub("plasticos","plastico", x, fixed = TRUE)
  x <- gsub("plasticas","plastico", x, fixed = TRUE)
  x <- gsub("plastica?","plastico", x, fixed = TRUE)
  x <- gsub("publicidades","publicidad", x, fixed = TRUE)
  x <- gsub("publicos","publico", x, fixed = TRUE)
  x <- gsub("publicos","publico", x, fixed = TRUE)
  x <- gsub("^memelas?","quesadillas", x, fixed = TRUE)
  x <- gsub("^gorditas?","quesadillas", x, fixed = TRUE)
  x <- gsub("venta de gorditas","quesadillas", x, fixed = TRUE)
  x <- gsub("^memelitas?","quesadillas", x, fixed = TRUE)
  x <- gsub("^tayoyos?","quesadillas", x, fixed = TRUE)
  x <- gsub("^tlacoyos?","quesadillas", x, fixed = TRUE)
  x <- gsub("^molotes?","quesadillas", x, fixed = TRUE)
  x <- gsub("^molotitos?","quesadillas", x, fixed = TRUE)
  x <- gsub("^quesos?","cremeria", x, fixed = TRUE)
  x <- gsub("^queso?","cremeria", x, fixed = TRUE)
  x <- gsub("^queseria?","cremeria", x, fixed = TRUE)
  x <- gsub("recauderia","polleria", x, fixed = TRUE)
  x <- gsub("rrecauderia","polleria", x, fixed = TRUE)
  x <- gsub("recaudo","polleria", x, fixed = TRUE)
  x <- gsub("recauder","polleria", x, fixed = TRUE)
  x <- gsub("recaudaria","polleria", x, fixed = TRUE)
  x <- gsub("recuaderia","polleria", x, fixed = TRUE)
  x <- gsub("venta de pollo","polleria", x, fixed = TRUE)
  x <- gsub("recicla?","reciclaje", x, fixed = TRUE)
  x <- gsub("reciclar","reciclaje", x, fixed = TRUE)
  x <- gsub("recicladora","reciclaje", x, fixed = TRUE)
  x <- gsub("refacciones","refaccionaria", x, fixed = TRUE)
  x <- gsub("refacciioniria","refaccionaria", x, fixed = TRUE)
  x <- gsub("refaccioniria","refaccionaria", x, fixed = TRUE)
  x <- gsub("refrescos","refresquera", x, fixed = TRUE)
  x <- gsub("refresqueria","refresquera", x, fixed = TRUE)
  x <- gsub("venta de refresquera","refresquera", x, fixed = TRUE)
  x <- gsub("tienda de refresquera","refresquera", x, fixed = TRUE)
  x <- gsub("venta de refresco","refresquera", x, fixed = TRUE)
  x <- gsub("reposteri?","pasteleria", x, fixed = TRUE)
  x <- gsub("reposteria","pasteleria", x, fixed = TRUE)
  x <- gsub("pasteles","pasteleria", x, fixed = TRUE)
  x <- gsub("comercio al por menor de dulceria y materias primas para pasteleria",
            "pasteleria", x, fixed = TRUE)
  x <- gsub("reumatologo","reumatologia", x, fixed = TRUE)
  x <- gsub("reumatologos","reumatologia", x, fixed = TRUE)
  x <- gsub("reumatologas","reumatologia", x, fixed = TRUE)
  x <- gsub("reumatologa","reumatologia", x, fixed = TRUE)
  x <- gsub("ripida","rapida", x, fixed = TRUE)
  x <- gsub("ripido","rapido", x, fixed = TRUE)
  x <- gsub("roldin","roldan", x, fixed = TRUE)
  x <- gsub("rostiseria","rosticeria", x, fixed = TRUE)
  x <- gsub("rotulacion","rotulos", x, fixed = TRUE)
  x <- gsub("rotulo","rotulos", x, fixed = TRUE)
  x <- gsub("salon de fiestas","salon social", x, fixed = TRUE)
  x <- gsub("jardin de fiestas","salon social", x, fixed = TRUE)
  x <- gsub("jardin de eventos","salon social", x, fixed = TRUE)
  x <- gsub("salon de eventos","salon social", x, fixed = TRUE)
  x <- gsub("sanitarios","bano", x, fixed = TRUE)
  x <- gsub("sanitario publico","bano", x, fixed = TRUE)
  x <- gsub("sanitarios publicos","bano", x, fixed = TRUE)
  x <- gsub("banos publicos","bano", x, fixed = TRUE)
  x <- gsub("bano publicos","bano", x, fixed = TRUE)
  x <- gsub("bano","bano publico", x, fixed = TRUE)
  x <- gsub("sabastiin","sebasian", x, fixed = TRUE)
  x <- gsub("sabastiin","sebasian", x, fixed = TRUE)
  x <- gsub("sn","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nomrbe?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nomre?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nobre?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin noombre?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nombbre?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nombr?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nomb? re?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nombfre","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nombrre","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nomrbe","sin nombre", x, fixed = TRUE)
  x <- gsub("sin noimbre","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nombe?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nonmbre","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nonmre","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nombtre","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nomber","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nonbre","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nomvre","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nombrte","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nom?","sin nombre", x, fixed = TRUE)
  x <- gsub("sin nombre","", x, fixed = TRUE)
  x <- gsub("t0rteria","torteria", x, fixed = TRUE)
  x <- gsub("tortas","torteria", x, fixed = TRUE)
  x <- gsub("venta de torteria","torteria", x, fixed = TRUE)
  x <- gsub("talachas","talacheria", x, fixed = TRUE)
  x <- gsub("talachitas","talacheria", x, fixed = TRUE)
  x <- gsub("talcheria","talacheria", x, fixed = TRUE)
  x <- gsub("tamales","tamaleria", x, fixed = TRUE)
  x <- gsub("tamales","tamaleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tamaleria","tamaleria", x, fixed = TRUE)
  x <- gsub("venta de tamaleria","tamaleria", x, fixed = TRUE)
  x <- gsub("tortillas","tortilla", x, fixed = TRUE)
  x <- gsub("tortilla","tortilleria", x, fixed = TRUE)
  x <- gsub("^tortilla ?","tortilleria", x, fixed = TRUE)
  x <- gsub("^tortilla  ?","tortilleria", x, fixed = TRUE)
  x <- gsub("tortills","tortillería", x, fixed = TRUE)
  x <- gsub("tortilla[:sapce:]","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilla?","tortilleria", x, fixed = TRUE)
  x <- gsub("tortelleria","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilliria","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleri?","tortilleria", x, fixed = TRUE)
  x <- gsub("tortillerpia","tortilleria", x, fixed = TRUE)
  x <- gsub("trtilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("verduras","verdura", x, fixed = TRUE)
  x <- gsub("frutas","fruta", x, fixed = TRUE)
  x <- gsub("platanos","fruta", x, fixed = TRUE)
  x <- gsub("legumbres","legumbre", x, fixed = TRUE)
  x <- gsub("verdularia","frutas y verduras", x, fixed = TRUE)
  x <- gsub("vetirinaria","veterinaria", x, fixed = TRUE)
  x <- gsub("vetirinario","veterinaria", x, fixed = TRUE)
  x <- gsub("veterinario","veterinaria", x, fixed = TRUE)
  x <- gsub("veterinirio","veterinaria", x, fixed = TRUE)
  x <- gsub("veteriniria","veterinaria", x, fixed = TRUE)
  x <- gsub("regalos y novedades","regalos", x, fixed = TRUE)
  x <- gsub("novedades y regalos","regalos", x, fixed = TRUE)
  x <- gsub("^novedades?","regalos", x, fixed = TRUE)
  x <- gsub("molino de nixtamal","molino", x, fixed = TRUE)
  x <- gsub("molienda de nixtamal","molino", x, fixed = TRUE)
  x <- gsub("molino para nixtamal","molino", x, fixed = TRUE)
  x <- gsub("servicio de molino de nixtamal","molino", x, fixed = TRUE)
  x <- gsub("venta de ropa","tienda de ropa", x, fixed = TRUE)
  x <- gsub("comercio al por menor de ropa","tienda de ropa", x, fixed = TRUE)
  x <- gsub("local de ropa","tienda de ropa", x, fixed = TRUE)
  x <- gsub("boutique","tienda de ropa", x, fixed = TRUE)
  x <- gsub("butique","tienda de ropa", x, fixed = TRUE)
  x <- gsub("bazar de ropa","tienda de ropa usada", x, fixed = TRUE)
  x <- gsub("^bazar?","tienda de ropa usada", x, fixed = TRUE)
  x <- gsub("^bazar[:space:]","tienda de ropa usada", x, fixed = TRUE)
  x <- gsub("venta de ropa usada","tienda de ropa usada", x, fixed = TRUE)
  x <- gsub("comercio al por menor de ropa, excepto de bebe y lenceria",
            "tienda de ropa", x, fixed = TRUE)
  x <- gsub("^ropa?","tienda de ropa", x, fixed = TRUE)
  x <- gsub("video-juegos","videojuegos", x, fixed = TRUE)
  x <- gsub("renta de maquinitas","videojuegos", x, fixed = TRUE)
  x <- gsub("maquinitas","videojuegos", x, fixed = TRUE)
  x <- gsub("video juegos","videojuegos", x, fixed = TRUE)
  x <- gsub("videojuego?","videojuegos", x, fixed = TRUE)
  x <- gsub("servicio de videojuegos","videojuegos", x, fixed = TRUE)
  x <- gsub("vidreria","vidrieria", x, fixed = TRUE)
  x <- gsub("vidieria","vidrieria", x, fixed = TRUE)
  x <- gsub("vidireria","vidrieria", x, fixed = TRUE)
  x <- gsub("vineria","vinateria", x, fixed = TRUE)
  x <- gsub("vinos","vinateria", x, fixed = TRUE)
  x <- gsub("vizquez","vazquez", x, fixed = TRUE)
  x <- gsub("zapatos","zapateria", x, fixed = TRUE)
  x <- gsub("zapaterias","zapateria", x, fixed = TRUE)
  x <- gsub("venta de zapateria","zapateria", x, fixed = TRUE)
  x <- gsub("tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria hechas a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria de comal","tortilleria", x, fixed = TRUE)
  x <- gsub("venta de tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("tienda diconsa","diconsa", x, fixed = TRUE)
  x <- gsub("tienda comunitaria diconsa","diconsa", x, fixed = TRUE)
  x <- gsub("fruteria y verdulerias","frutas y verduras", x, fixed = TRUE)
  x <- gsub("fruteria y verduleria","frutas y verduras", x, fixed = TRUE)
  x <- gsub("fruteria","frutas y verduras", x, fixed = TRUE)
  x <- gsub("fruta y legumbre","frutas y verduras", x, fixed = TRUE)
  x <- gsub("verdura y legumbre","frutas y verduras", x, fixed = TRUE)
  x <- gsub("venta de productos de limpieza","productos de limpieza", x, fixed = TRUE)
  x <- gsub("venta de verdura","frutas y verduras", x, fixed = TRUE)
  x <- gsub("venta de fruta y verdura","frutas y verduras", x, fixed = TRUE)
  x <- gsub("comercio al por menor de fruta y verdura frescas","frutas y verduras",
            x, fixed = TRUE)
  x <- gsub("verduleria","frutas y verduras", x, fixed = TRUE)
  x <- gsub("venta de fruta","frutas y verduras", x, fixed = TRUE)
  x <- gsub("puesto de verdura","frutas y verduras", x, fixed = TRUE)
  x <- gsub("fruta y verdura frescas","frutas y verduras", x, fixed = TRUE)
  x <- gsub("fruta y verdura","frutas y verduras", x, fixed = TRUE)
  x <- gsub("^verdura?","frutas y verduras", x, fixed = TRUE)
  x <- gsub("^fruta?","frutas y verduras", x, fixed = TRUE)
  x <- gsub("^legumbre?","frutas y verduras", x, fixed = TRUE)
  x <- gsub("^verdura[:space:]","frutas y verduras", x, fixed = TRUE)
  x <- gsub("^fruta[:space:]","frutas y verduras", x, fixed = TRUE)
  x <- gsub("^legumbre[:space:]","frutas y verduras", x, fixed = TRUE)
  x <- gsub("tortilleria de mano","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilleria hechas a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilla","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria hechas a mano en comal","tortilleria", x, fixed = TRUE)
  x <- gsub("venta de quesadillas","quesadillas", x, fixed = TRUE)
  x <- gsub("venta de tortilleria y gorditas","quesadillas", x, fixed = TRUE)
  x <- gsub("venta de tortilleria y antojitos","quesadillas", x, fixed = TRUE)
  x <- gsub("gorditas y tortilleria","quesadillas", x, fixed = TRUE)
  x <- gsub("elaboracion y venta de tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("venta de tortilleria de comal","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria de maiz","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria y gorditas","quesadillas", x, fixed = TRUE)
  x <- gsub("se vende tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("venta de tortilleria y gorditas","quesadillas", x, fixed = TRUE)
  x <- gsub("se venden tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion de tortilleria a mano de maiz","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion y venta de tortilleria hechas a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion y tortilleria hechas a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion y tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("elaboracion a mano de tortilleria de maiz","tortilleria", x, fixed = TRUE)
  x <- gsub("venta de tortilleria y tlacoyos","quesadillas", x, fixed = TRUE)
  x <- gsub("elaboracion de quesadillas","quesadillas", x, fixed = TRUE)
  x <- gsub("puesto de quesadillas","quesadillas", x, fixed = TRUE)
  x <- gsub("puesto de fruta","frutas y verduras", x, fixed = TRUE)
  x <- gsub("venta de tortilleria sin nomre","tortilleria", x, fixed = TRUE)
  x <- gsub("expendio de tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("local de tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("local de tortilleria hechas a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("negocio de tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("negocio de tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("puesto de tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("puesto de tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("preparacion de tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("produccion de tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("preparacion y tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("tienda de tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("se hace tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("se hacen tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("se venden tortilleria","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria a mano","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria de mano","tortilleria", x, fixed = TRUE)
  x <- gsub("tortilleria a amano","tortilleria", x, fixed = TRUE)
  x <- gsub("comercio al por menor de frutas y verduras frescas","frutas y verduras",
            x, fixed = TRUE)
  x <- gsub("comercio al por menor de frutas y verdura frescas","frutas y verduras",
            x, fixed = TRUE)
  x <- gsub("comercio al por menor de articulos usados","tienda de articulos usados",
            x, fixed = TRUE)
  x <- gsub("petates","petate", x, fixed = TRUE)
  x <- gsub("^petate?","elaboracion de petate", x, fixed = TRUE)
  x <- gsub("elaboracion de petate de palma","elaboracion de petate", x, fixed = TRUE)
  x <- gsub("venta de tortilla","tortilleria", x, fixed = TRUE)
  x <- gsub("cfe?","comision federal de electricidad", x, fixed = TRUE)
  x <- gsub("comida corrida","cocina economica", x, fixed = TRUE)
  x <- gsub("lecheria liconsa","liconsa", x, fixed = TRUE)
  x <- gsub("taller de alfareria","alfareria", x, fixed = TRUE)
  x <- gsub("taller de articulos de alfareria","alfareria", x, fixed = TRUE)
  x <- gsub("fabricacion de articulos de alfareria porcelana y loza","alfareria",
            x, fixed = TRUE)
  x <- gsub("por ciento","%", x, fixed = TRUE)
  x <- gsub("100%[:alnum:]","100% [:alnum:]", x, fixed = TRUE)
  x <- gsub("pinturas comex","comex", x, fixed = TRUE)
  x <- gsub("0ficina","oficina", x, fixed = TRUE)
  x <- gsub("aceites","aceite", x, fixed = TRUE)
  x <- gsub("aceros","acero", x, fixed = TRUE)
  x <- gsub("lubricantes","lubricante", x, fixed = TRUE)
  gsub("herbalife ", "herbalife", x, fixed = TRUE)
  gsub("club de nutricion de herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de herbalife", "herbalife", x, fixed = TRUE)
  gsub("venta de herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador de herbalife", "herbalife", x, fixed = TRUE)
  gsub("venta de productos de herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife club de nutricion", "herbalife", x, fixed = TRUE)
  gsub("club de herbalife", "herbalife", x, fixed = TRUE)
  gsub("compra herbalife ", "herbalife", x, fixed = TRUE)
  gsub("desayunador nutricionales herbalife", "herbalife", x, fixed = TRUE)
  gsub("distribuidor independiente herbalife", "herbalife", x, fixed = TRUE)
  gsub("productos de herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador nutritivos herbalife ", "herbalife", x, fixed = TRUE)
  gsub("club herbalife", "herbalife", x, fixed = TRUE)
  gsub("tienda de herbalife", "herbalife", x, fixed = TRUE)
  gsub("productos de herbalife.", "herbalife", x, fixed = TRUE)
  gsub("herbalife.", "herbalife", x, fixed = TRUE)
  gsub("club de la herbalife", "herbalife", x, fixed = TRUE)
  gsub("venta de productos naturistas herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador nutritivos herbalife", "herbalife", x, fixed = TRUE)
  gsub("suplementos alimenticios herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de atencion a clientes herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de nutricion de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("compra herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("tienda naturista herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("herbalife suplementos alimenticios", "herbalife", x, fixed = TRUE)
  gsub("venta de licuados herbalife ", "herbalife", x, fixed = TRUE)
  gsub("complementos alimenticios de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("venta de producto herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("venta de productos naturales herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador nutricional herbalife", "herbalife", x, fixed = TRUE)
  gsub("club nutricional de herbalife", "herbalife", x, fixed = TRUE)
  gsub("licuados herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunadores herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador herbalite", "herbalife", x, fixed = TRUE)
  gsub("establecimiento de herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife puebla", "herbalife", x, fixed = TRUE)
  gsub("club de salud y bienestar herbalife", "herbalife", x, fixed = TRUE)
  gsub("malteadas de herbalife", "herbalife", x, fixed = TRUE)
  gsub("clun de herbalife", "herbalife", x, fixed = TRUE)
  gsub("club herbalife ", "herbalife", x, fixed = TRUE)
  gsub("comedor herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife y zumba, ", "herbalife", x, fixed = TRUE)
  gsub("centro de apoyo herbalife huauchinango", "herbalife", x, fixed = TRUE)
  gsub("preparacion de bebidas herbalife", "herbalife", x, fixed = TRUE)
  gsub("compra de herbalife", "herbalife", x, fixed = TRUE)
  gsub("suplementos alimenticios de herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de nutricion de herbalife", "herbalife", x, fixed = TRUE)
  gsub("club nutricinal herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de reclutamiento herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife v-cac-economic", "herbalife", x, fixed = TRUE)
  gsub("compra venta de productos naturistas herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de nutricion distribuidor independiente de herbalife", "herbalife", x, fixed = TRUE)
  gsub("compra venta de suplementos alimenticios herbalife ", "herbalife", x, fixed = TRUE)
  gsub("nutricion de herbalife", "herbalife", x, fixed = TRUE)
  gsub("compra y herbalife", "herbalife", x, fixed = TRUE)
  gsub("productos de complemento alimenticio herbalife", "herbalife", x, fixed = TRUE)
  gsub("compra-herbalife", "herbalife", x, fixed = TRUE)
  gsub("productos naturistas herbalife", "herbalife", x, fixed = TRUE)
  gsub("coplemento alimenticio herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de distribucion herbalife ", "herbalife", x, fixed = TRUE)
  gsub("dasayunos herbalife", "herbalife", x, fixed = TRUE)
  gsub("club herbalite", "herbalife", x, fixed = TRUE)
  gsub("desayunadoes herbalife", "herbalife", x, fixed = TRUE)
  gsub("club nutriciona herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife suplementos alimenticios ", "herbalife", x, fixed = TRUE)
  gsub("centro nutricional herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife y clases de zumba y king boxing", "herbalife", x, fixed = TRUE)
  gsub("desayunador de nutritivos herbalife", "herbalife", x, fixed = TRUE)
  gsub("jugueria de herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador de productos alimenticio herbalife ", "herbalife", x, fixed = TRUE)
  gsub("local de herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro nutricional herbalite", "herbalife", x, fixed = TRUE)
  gsub("negocio de venta de productos naturistas herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador nutricinales herbalife", "herbalife", x, fixed = TRUE)
  gsub("oficinas de capacitacion herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de bienestar y herbalife ", "herbalife", x, fixed = TRUE)
  gsub("prestacion de servicios de herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador nutricionales de herbalife", "herbalife", x, fixed = TRUE)
  gsub("productos de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("centro de alimentacion herbalife", "herbalife", x, fixed = TRUE)
  gsub("productos de plistico y herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador nutricionales herbalife tonic life", "herbalife", x, fixed = TRUE)
  gsub("servicio de herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador nutritivo herbalife", "herbalife", x, fixed = TRUE)
  gsub("suplementos alimenticios, herbalife.", "herbalife", x, fixed = TRUE)
  gsub("centro de atencion al cliente herbalife", "herbalife", x, fixed = TRUE)
  gsub("tienda de productos naturales herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de bienestar herbalife", "herbalife", x, fixed = TRUE)
  gsub("venta de batidos de herbalife", "herbalife", x, fixed = TRUE)
  gsub("desayunador y cenas herbalife", "herbalife", x, fixed = TRUE)
  gsub("club nuitricion herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de la herbalife ", "herbalife", x, fixed = TRUE)
  gsub("venta de productos de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("desayuno herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de apoyo herbalife", "herbalife", x, fixed = TRUE)
  gsub("dessayunos herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de capacitacion de herbalife", "herbalife", x, fixed = TRUE)
  gsub("desuyanador herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife tehuacin", "herbalife", x, fixed = TRUE)
  gsub("desuyunos herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife venta", "herbalife", x, fixed = TRUE)
  gsub("desuyunos nutritivos herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife y venta de chiles en vinagre la corregidora", "herbalife", x, fixed = TRUE)
  gsub("distribucion herbalife", "herbalife", x, fixed = TRUE)
  gsub("centro de capacitacion oficina de herbalife", "herbalife", x, fixed = TRUE)
  gsub("distribuidor de herbalife", "herbalife", x, fixed = TRUE)
  gsub("jugueria y productos naturistas herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de nuricion herbalife", "herbalife", x, fixed = TRUE)
  gsub("licuados y te de productos de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("distribuidora de herbalife", "herbalife", x, fixed = TRUE)
  gsub("local de productos de herbalife", "herbalife", x, fixed = TRUE)
  gsub("distribuidora herbalife", "herbalife", x, fixed = TRUE)
  gsub("negocio de herbalife", "herbalife", x, fixed = TRUE)
  gsub("distribuidora independiente herbalife", "herbalife", x, fixed = TRUE)
  gsub("nucell herbalife", "herbalife", x, fixed = TRUE)
  gsub("distrubuidora herbalife", "herbalife", x, fixed = TRUE)
  gsub("oficina distribuidora independiente de herbalife", "herbalife", x, fixed = TRUE)
  gsub("elaboracion de malteadas herbalife", "herbalife", x, fixed = TRUE)
  gsub("oficinas de herbalife", "herbalife", x, fixed = TRUE)
  gsub("venta de productos nutricionales herbalife", "herbalife", x, fixed = TRUE)
  gsub("preparacion de suplementos alimenticios herbalife ", "herbalife", x, fixed = TRUE)
  gsub("venta de productos nutricionales herbalife ", "herbalife", x, fixed = TRUE)
  gsub("productos alimenticios herbalife ", "herbalife", x, fixed = TRUE)
  gsub("venta de suplementos alimenticios herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de nutricion privado de herbalife", "herbalife", x, fixed = TRUE)
  gsub("venta herbalife", "herbalife", x, fixed = TRUE)
  gsub("productos de herbalife licuados", "herbalife", x, fixed = TRUE)
  gsub("bebidas alimenticias herbalife", "herbalife", x, fixed = TRUE)
  gsub("productos de nutricion de herbalife", "herbalife", x, fixed = TRUE)
  gsub("grupo de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("productos naturista herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de nuticion herbalife", "herbalife", x, fixed = TRUE)
  gsub("promocion de menbresias herbalife", "herbalife", x, fixed = TRUE)
  gsub("club de nutriccion de herbalife", "herbalife", x, fixed = TRUE)
  gsub("spinning y herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife centro de apoyo", "herbalife", x, fixed = TRUE)
  gsub("club e herbalife ", "herbalife", x, fixed = TRUE)
  gsub("club de nutricion celular herbalife", "herbalife", x, fixed = TRUE)
  gsub("suplementos herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife club nutricional", "herbalife", x, fixed = TRUE)
  gsub("tienda de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("herbalife complementos alimenticios", "herbalife", x, fixed = TRUE)
  gsub("tienda de ropa y herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife desayunador", "herbalife", x, fixed = TRUE)
  gsub("venta de alimentos herbalife ", "herbalife", x, fixed = TRUE)
  gsub("herbalife desayunador ", "herbalife", x, fixed = TRUE)
  gsub("venta de complementos alimenticios herbalife ", "herbalife", x, fixed = TRUE)
  gsub("herbalife fanny", "herbalife", x, fixed = TRUE)
  gsub("venta de licuados herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife guadalupe", "herbalife", x, fixed = TRUE)
  gsub("venta de prodcutos herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife guadalupe de ita", "herbalife", x, fixed = TRUE)
  gsub("club nutricion herbalite", "herbalife", x, fixed = TRUE)
  gsub("herbalife independencia", "herbalife", x, fixed = TRUE)
  gsub("venta de productos herbalite", "herbalife", x, fixed = TRUE)
  gsub("herbalife independiente", "herbalife", x, fixed = TRUE)
  gsub("venta de productos naturales herbalife ", "herbalife", x, fixed = TRUE)
  gsub("herbalife naturista", "herbalife", x, fixed = TRUE)
  gsub("club social herbalife", "herbalife", x, fixed = TRUE)
  gsub("herbalife preparacion de te y licuados ", "herbalife", x, fixed = TRUE)
  gsub("venta de productos suplementos herbalife", "herbalife", x, fixed = TRUE)
  gsub("establecimiento de herbalife marga", "herbalife", x, fixed = TRUE)
  gsub("venta de suplementos alimenticios herbalife ", "herbalife", x, fixed = TRUE)
  gsub("estanquillo herbalife", "herbalife", x, fixed = TRUE)
  gsub("venta por comision de herbalife y zapateria", "herbalife", x, fixed = TRUE)
  gsub("expendio de herbalife ", "herbalife", x, fixed = TRUE)
  gsub("grupo de herbalife", "herbalife", x, fixed = TRUE)
  x
}

corta.nom$nom_estab <-uni2latex(corta.nom$nom_estab)
corta.nom$raz_social <-uni2latex(corta.nom$raz_social)
corta.nom$nombre_act <-uni2latex(corta.nom$nombre_act)

corta.nom1 <- subset(corta.nom, select = c("id", "nom_estab", "raz_social", 
                                           "nombre_act"))

corta.nom1$largo_n <- sapply(gregexpr("\\S+", corta.nom1$nom_estab), length)
corta.nom1$largo_r <- sapply(gregexpr("\\S+", corta.nom1$raz_social), length)
corta.nom1$snomn <- regexpr("sin nombre", corta.nom1$nom_estab)
corta.nom1$snomr <- regexpr("sin nombre", corta.nom1$raz_social)
corta.nom1$ncharn <- nchar(corta.nom1$nom_estab, type = "chars")
corta.nom1$snomn1 <- grepl("sin nombre", corta.nom1$nom_estab)
corta.nom1$snomr1 <- grepl("sin nombre", corta.nom1$raz_social)
corta.nom1$nombre_act <- as.character(corta.nom1$nombre_act)

corta.nom1$desc_ue <- if (corta.nom1$snomn1==T) substr(corta.nom1$nom_estab,
                                                       1, corta.nom1$snomn - 1) else 
                      substr(corta.nom1$nom_estab, 1, corta.nom1$nchar)

#corta.nom1$nom_estab[grepl("sin nombre", corta.nom1$nom_estab)] <- "sin nombre"
tabnom <- as.data.frame(table(corta.nom1$nom_estab))
names(tabnom)

write.csv(tabnom, file = "C:\\Users\\Ruben\\Documents\\Datos\\denue_21_shp\\conjunto_de_datos\\tabfreq_nom_21_1.csv", sep = ",", fileEncoding = "UTF-8")

nomsep <- strsplit(as.character(corta.nom1$nom_estab), " ")

nomsep1 <- data.frame(corta.nom1, do.call(rbind, nomsep))

nomsep1$X1	<-	as.character(nomsep1$X1)
nomsep1$X2	<-	as.character(nomsep1$X2)
nomsep1$X3	<-	as.character(nomsep1$X3)
nomsep1$X4	<-	as.character(nomsep1$X4)
nomsep1$X5	<-	as.character(nomsep1$X5)
nomsep1$X6	<-	as.character(nomsep1$X6)
nomsep1$X7	<-	as.character(nomsep1$X7)
nomsep1$X8	<-	as.character(nomsep1$X8)
nomsep1$X9	<-	as.character(nomsep1$X9)
nomsep1$X10	<-	as.character(nomsep1$X10)
nomsep1$X11	<-	as.character(nomsep1$X11)
nomsep1$X12	<-	as.character(nomsep1$X12)
nomsep1$X13	<-	as.character(nomsep1$X13)
nomsep1$X14	<-	as.character(nomsep1$X14)
nomsep1$X15	<-	as.character(nomsep1$X15)
nomsep1$X16	<-	as.character(nomsep1$X16)
nomsep1$X17	<-	as.character(nomsep1$X17)
nomsep1$X18	<-	as.character(nomsep1$X18)
nomsep1$X19	<-	as.character(nomsep1$X19)
nomsep1$X20	<-	as.character(nomsep1$X20)
nomsep1$X21	<-	as.character(nomsep1$X21)
nomsep1$X22	<-	as.character(nomsep1$X22)


#View(nomsep1)

nomsep_l1 <- nomsep1[nomsep1$largo_n==1, ]
nomsep_l2 <- nomsep1[nomsep1$largo_n==2, ]
nomsep_l3 <- nomsep1[nomsep1$largo_n==3, ]
nomsep_l4 <- nomsep1[nomsep1$largo_n==4, ]
nomsep_l5 <- nomsep1[nomsep1$largo_n==5, ]
nomsep_l6 <- nomsep1[nomsep1$largo_n==6, ]
nomsep_l7 <- nomsep1[nomsep1$largo_n==7, ]
nomsep_l8 <- nomsep1[nomsep1$largo_n==8, ]
nomsep_l9 <- nomsep1[nomsep1$largo_n==9, ]
nomsep_l10 <- nomsep1[nomsep1$largo_n==10, ]
nomsep_l11 <- nomsep1[nomsep1$largo_n==11, ]
nomsep_l12m <- nomsep1[nomsep1$largo_n>=12, ]

nomsep_l1	<- 	nomsep_l1[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1")]
nomsep_l2	<- 	nomsep_l2[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2")]
nomsep_l3	<- 	nomsep_l3[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3")]
nomsep_l4	<- 	nomsep_l4[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3", "X4")]
nomsep_l5	<- 	nomsep_l5[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3", "X4", "X5")]
nomsep_l6	<- 	nomsep_l6[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3", "X4", "X5",
                          "X6")]
nomsep_l7	<- 	nomsep_l7[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3", "X4", "X5",
                          "X6", "X7")]
nomsep_l8	<- 	nomsep_l8[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3", "X4", "X5",
                          "X6", "X7", "X8")]
nomsep_l9	<- 	nomsep_l9[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                          "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3", "X4", "X5",
                          "X6", "X7", "X8", "X9")]
nomsep_l10	<- 	nomsep_l10[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn"
                            , "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3", "X4", "X5",
                            "X6", "X7", "X8", "X9", "X10")]
nomsep_l11	<- 	nomsep_l11[c("id", "nom_estab", "raz_social", "nombre_act", "largo_n", "largo_r", "snomn",
                            "snomr", "ncharn", "snomn1", "snomr1", "desc_ue", "X1", "X2", "X3", "X4", "X5",
                            "X6", "X7", "X8", "X9", "X10", "X11")]

require(phonics)
require(stringdist)

nomsep_l1table <- as.data.frame(table(nomsep_l1$nom_estab))

nomsep_l1table <- nomsep_l1table[sort(nomsep_l1table$Freq, decreasing = T), ]

write.csv(nomsep_l1table, file = "C:\\Users\\Ruben\\Documents\\Datos\\denue_21_shp\\conjunto_de_datos\\nom_21_l1_1.csv", sep = ",", fileEncoding = "UTF-8")


# nomsep_l2table <- as.data.frame(table(nomsep_l2$nom_estab))
# 
# nomsep_l2table <- nomsep_l2table[sort(ascharacter(nomsep_l2table$Freq), decreasing = T), ]
# 
# 
# write.csv(nomsep_l2table, file = "C:\\Users\\Ruben\\Documents\\Datos\\denue_21_shp\\conjunto_de_datos\\nom_21_l2.csv", sep = ",", fileEncoding = "UTF-8")
